### ISSUE TITLE
Errors and conflicts

### ISSUE THREAD

**Issue by palash25** [p-society/typeracer-cli#15]
When I tried out the practice mode today I got this

```
net.js:705
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type number
    at WriteStream.Socket.write (net.js:705:11)
    at Timeout.setInterval (/home/palash25/Dev/Projects/psoc/typeracer-cli/scripts/game.js:146:14)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```

so I did a pull and I'm getting a merge conflict for some reason even though my repo is clean

```
 ✘ palash25@Lenovo-G50  ~  hack psoc
 palash25@Lenovo-G50  ~/Dev/Projects/psoc  cd typeracer-cli 
 palash25@Lenovo-G50  ~/Dev/Projects/psoc/typeracer-cli   master  git pull origin master
remote: Counting objects: 40, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 40 (delta 21), reused 39 (delta 20), pack-reused 0
Unpacking objects: 100% (40/40), done.
From https://github.com/p-society/typeracer-cli
 * branch            master     -> FETCH_HEAD
 + ed12cc1...121b8e2 master     -> origin/master  (forced update)
Auto-merging online/client.js
CONFLICT (content): Merge conflict in online/client.js
Automatic merge failed; fix conflicts and then commit the result.
 ✘ palash25@Lenovo-G50  ~/Dev/Projects/psoc/typeracer-cli   master ●✚ >M<  npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 1 package in 21.355s
 palash25@Lenovo-G50  ~/Dev/Projects/psoc/typeracer-cli   master ●✚ >M<  npm link
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 6.68s
/home/palash25/.npm-packages/bin/typerace -> /home/palash25/.npm-packages/lib/node_modules/typeracer-cli/index.js
/home/palash25/.npm-packages/lib/node_modules/typeracer-cli -> /home/palash25/Dev/Projects/psoc/typeracer-cli
 palash25@Lenovo-G50  ~/Dev/Projects/psoc/typeracer-cli   master ●✚ >M<  typerace p
/home/palash25/Dev/Projects/psoc/typeracer-cli/online/client.js:100
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/palash25/Dev/Projects/psoc/typeracer-cli/index.js:9:16)
```

cc @knrt10 @IamRaviTejaG

**Comment by knrt10** [comment]
@palash25 wait till I ping you. The error is because you have to update to latest veerison. Don't try anything for 30 min.

**Comment by palash25** [comment]
I'll try again at midnight so don't worry
